[meta]
display_name = "hr500k v1.0"
preselected = false

[general]
span = "s"
dialect = "Sketch Engine"

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "pos"
xpos = "tag"
feats = "feats"
id = "id"
head = "ud_dep_head_id"
deprel = "ud_dep"
