[meta]
display_name = "KZB (znanstvena dela)"
preselected = false

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "pos"
xpos = "tag"
feats = "feats"
id = "id"
head = "ud_head_id"
deprel = "ud_dep"
