[meta]
display_name = "meWaC (Montenegrin Web)"
preselected = false

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "ud_pos"
xpos = "tag"
feats = "ud_feats"
id = "id"
head = "ud_dep_head_id"
deprel = "ud_dep"
