[meta]
display_name = "ParlaMint-LT 2.1 (Lithuanian parliament)"
preselected = false

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "pos"
xpos = "pos"
feats = "feats"
id = "n"
head = "dep_head_n"
deprel = "dep"
