[meta]
display_name = "ParlaMint-HR 3.0 (Croatian parliament)"
preselected = false

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "pos"
xpos = "pos"
feats = "feats"
id = "id"
head = "dep_head_id"
deprel = "dep"
