[meta]
display_name = "Šolar: učenci (razvojni)"
preselected = false

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "pos"
xpos = "tag"
feats = "ud_feats"
id = "id"
head = "jos_head_id"
deprel = "jos_dep"
