[meta]
display_name = "SUK 1.1"
preselected = true
preferred = true

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "ud_pos"
xpos = "tag"
feats = "ud_feats"
id = "id"
head = "ud_head_id"
deprel = "ud_dep"
