[meta]
display_name = "Uganke (zbirka slovenskih ugank)"
preselected = false

[annotation_scheme]
form = "word"
lemma = "lemma"
upos = "pos"
xpos = "tag"
feats = "feats"
id = "id"
head = "dep_head_id"
deprel = "dep"
