name: CI

on:
  push:
    branches:
      - '**' # Run on all branches.

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Check source code formatting
        uses: psf/black@stable
        with:
          options: '--verbose --check --diff'
          src: 'src'
      - name: Install required tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install pylint
      - name: Run Pylint
        run: pylint src

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # List all supported python versions.
        python-version: [ '3.12', '3.13', '3.14' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Run unittest ${{ matrix.python-version }}
        run: python -m unittest
