[web]
branding = "https://www.clarin.si/info/wp-content/uploads/2014/08/Clarin-SI-logo.png"
homepage = "https://www.clarin.si/"
baseurl = "https://www.clarin.si/ske/#concordance?tab=advanced&queryselector=cql&showresults=1&corpname={corpus}&cql={query}"
system_name = "CLARIN.SI Sketch Engine"
corpus_configs = "configurations/clarin-si/corpora"
allow_external_search = true
